//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopProj222.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogin
    {
        public int id { get; set; }
        public Nullable<int> Emp_id { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
